remove(list=ls())
library(dplyr)
setwd("C:/Users/leef/Dropbox/Coursera_R_Stuff/Course_4_ExploratoryAnalysis/Project1")
mydf <- read.csv("household_power_consumption.txt", header=TRUE, sep=";",
                 stringsAsFactors=FALSE)
mydf<-mutate(mydf, NewDate=as.Date(Date,"%d/%m/%Y"))
mydf<-mutate(mydf, Year=as.numeric(substr(NewDate,start=1,stop=4)))
mydf<-mutate(mydf, Month=as.numeric(substr(NewDate,start=6,stop=7)))
mydf<-mutate(mydf, Day=as.numeric(substr(NewDate,start=9,stop=10)))
mydf<-mutate(mydf, Hour=as.numeric(substr(Time,start=1,stop=2)))
mydf<-mutate(mydf, Min=as.numeric(substr(Time,start=4,stop=5)))
mydf<-filter(mydf,Year==2007 & Month == 2 & Day <3)
mydf<-arrange(mydf,Year,Month,Day,Hour,Min)
Global_active_power<-as.numeric(mydf$Global_active_power)
myrows<-as.numeric(row.names(mydf))
plot(Global_active_power~myrows,type="n",ylab="Global Active Power (kilowatts)"
     ,xlab="",xaxt="n")
lines(myrows,Global_active_power,type="l")
axis(1,at=c(1,1440,2880),labels=c("Thu","Fri","Sat"))
dev.copy(png,file="plot2.png")
dev.off()